name = "KroneckerProductKernels"
uuid = "cdbd8a54-2c11-4475-85dd-323d022ca3c3"
authors = ["Zach Langford <langfzac@sas.upenn.edu> and contributors"]
version = "0.0.1"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
